[build]
builder = "NIXPACKS"

[deploy]
startCommand = "/bin/sh -c \"exec uvicorn bot:app --host 0.0.0.0 --port $PORT\""
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 